#!/usr/bin/env bash
cd $(dirname $0)
exec 1> sources.pro

list_headers=$(find src -name '*.h')
list_forms=$(find src -name '*.ui')
list_sources=$(find src -name '*.cpp')

echo 'DEPENDPATH = src'
echo 'INCLUDEPATH = src'
echo
echo "HEADERS *= ${list_headers}"
echo "FORMS *= ${list_forms}"
echo "SOURCES *= ${list_sources}"
